### ISSUE TITLE
In QuickStart make host-selection page always appear, to better support Docker

### ISSUE THREAD

**Issue by stuartMoorhouse** [marklogic/marklogic-data-hub#3080]
QuickStart by default creates a local environment, which expect MarkLogic at ``localhost``, however this means in a Dockerized enviroment we can't map ports to something else on our host.

Sometimes QuickStart lets us choose the host, but this doesn't always appear.

If we can always choose the host, it is easier to use QuickStart in a container.

**Comment by stuartMoorhouse** [comment]
To reproduce:

Start a MarkLogic host and QuickStart via docker-compose (``docker-compose up``)
Initialize the DHF via QuickStart
Stop the Docker stack (``docker-compose stop``)
Restart the Docker stack (``docker-compose up``)

The only way to ensure that I see the host-selection page is to run ``docker-compose down``, which is less convenient than using "up" and "stop" with the whole stack. 

This is my docker-compose.yml, for reference:

```
version: '3.7'

networks:
  marklogicDHF:

services:
    marklogic.dhf.local:
      image: store/marklogicdb/marklogic-server:${ML_VERSION}
      hostname: marklogic.dhf.local
      container_name: marklogic.dhf.local
      environment:
        - MARKLOGIC_INIT=true
        - MARKLOGIC_ADMIN_USERNAME=${ADMIN}
        - MARKLOGIC_ADMIN_PASSWORD=${PASSWORD}
        - TZ=Europe/Prague
      ports:
        - 17997-18025:7997-8025
      volumes:
        - ./volumes/marklogic.dhf.local/:/var/opt/MarkLogic/
      networks:
        - marklogicDHF

    quick.start.local:
      build: 
        context: .
        dockerfile: quickstart.Dockerfile
        args:
        - quickstart_download_url=${QUICK_START_URL}
      depends_on:     
        - marklogic.dhf.local
      hostname: quick_start.local
      container_name: quick_start.local
      ports:
       - 9080:8080
      networks:
        - marklogicDHF   
      volumes:
       - ./DHF-config:/DHF-config
       - ./data:/data
```
